service: s3-signed-urls

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  environment:
    AWS_BUCKET_NAME: s3-bucket-operations 
    METADATA_TABLE: s3-objects-metadata
    
  iamRoleStatements:   # 👈 yahan S3 ke permissions dene honge
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
        - s3:DeleteObject
        - dynamodb:PutItem  
        - dynamodb:DeleteItem

        
      Resource:
        - arn:aws:s3:::s3-bucket-operations
        - arn:aws:s3:::s3-bucket-operations/*
        - arn:aws:dynamodb:us-east-1:*:table/s3-objects-metadata
  # apna bucket name daalna

functions:
  getSignedUrlUpload:
    handler: handler.getSignedUrlUpload
    events:
      - http:
          path: upload-url
          method: post

  getSignedUrlGet:
    handler: handler.getSignedUrlGet
    events:
      - http:
          path: get-url
          method: get

  saves3metadata:
    handler: handler.saveMetadata
    events: 
      - s3:
          bucket: s3-bucket-operations
          existing: true
          event: s3:ObjectCreated:Put

  deletes3object:               # 👈 New Lambda
    handler: handler.deletes3object
    events:
      - http:
          path: delete-file/{id+}
          method: delete

resources:
  Resources:
  
    FilesMetaDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: s3-objects-metadata
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH